AllCops:
  TargetRubyVersion: 2.4

LineLength:
  Max: 125

StringLiterals:
  EnforcedStyle: single_quotes

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false
